version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - mkdir -p deploy
      - cp -r dist/* deploy/
artifacts:
  files:
    - '**/*'
  base-directory: deploy
